# Settings for the app
app:
  # HTML Title
  title: North Seattle Network
  # Header name
  name: "North Seattle Network"
  # Meta description that will show up in Google search results
  meta_description: "_( )"
  # Meta author that will show up in Google search results
  meta_author: HaxGeo.org

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

languages:
  - code: es
    label: Hablo Español

  - code: en
    label: I Speak English


#   - code: vi
#     label: tôi nói tiếng việt

map:
# Settings for map and layer configs
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true
  #  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 47.54406
      lng: -122.36087
    zoom: 14
    minZoom: 1
    maxZoom: 18
  layers:
    # SmarterCleanup Mapbox base layer:
    - id: osm
      url: //api.tiles.mapbox.com/v4/heyduwamishcore.3fd2d9aa/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiaGV5ZHV3YW1pc2hjb3JlIiwiYSI6ImNpaTEyNDNtdjAwMG10OW0wYzFtYmlsZXgifQ.yfrIdudUO9j_lKNtTZQU-g
      attribution: '<a href="/page/terms">Terms and conditions</a> &copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Mapbox</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'
      type: basemap

    - id: satellite
      url: //api.tiles.mapbox.com/v4/smartercleanup.pe3o4gdn/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'
      type: basemap

    - id: light
      url: //api.mapbox.com/styles/v1/smartercleanup/cizhuxpgi00042so2kw8c1lfl/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: 'Hello World'
      type: basemap

    - id: outdoor
      url: //api.mapbox.com/styles/v1/smartercleanup/cir0yq1nl001lbsnh22c6747c/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: 'Hello World'
      type: basemap

  # Legend Layers
    - id: ymca
      type: place
      slug: ymca

# The values map the place type to map icons (defined below).
place_types:

  mapboxZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [50, 50]
        iconAnchor: [25, 25]
    - condition: '{{map.zoom}} < 16'
      icon:
        iconSize: [20, 20]
        iconAnchor: [10, 10]
    - condition: '{{map.zoom}} >= 16'
      icon:
        iconSize: [30, 30]
        iconAnchor: [15, 15]

  roundZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [50, 50]
        iconAnchor: [25, 25]
    - condition: '{{map.zoom}} < 11'
      icon:
        iconSize: [20, 20]
        iconAnchor: [10, 10]
    - condition: '{{map.zoom}} >= 11'
      icon:
        iconSize: [30, 30]
        iconAnchor: [15, 15]

  teardropZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [50, 60]
        iconAnchor: [25, 25]
        shadowSize: [50, 60]
        shadowAnchor: [14, 60]
    - condition: '{{map.zoom}} < 11'
      icon:
        iconSize: [20, 24]
        iconAnchor: [10, 24]
    - condition: '{{map.zoom}} >= 11'
      icon:
        iconSize: [38, 46]
        iconAnchor: [19, 46]

  network_org:
    zoomType: teardropZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/network-marker.png


# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  # A panel's icon is a icon's name taken from here:
  # https://fortawesome.github.io/Font-Awesome/icons/
  panels:
    - id: gis-layers
      icon: list
      view: GISLegendView
      title: _(Map Layers:)
      basemaps:
        - id: osm
          title: _(OpenStreetMap)
          visibleDefault: false
        - id: satellite
          title: _(Satellite View)
          visibleDefault: true
        - id: light
          title: _(Light)
          visibleDefault: false
        - id: outdoor
          title: _(Outdoor)
          visibleDefault: false
      groupings:
        - id: grp-community
          title: _(Community Data)
          visibleDefault: true
          layers:
            - id: ymca
              title: _(North Seattle Organizations)
              visibleDefault: true

    - id: ticker
      view: ActivityView
      icon: comments-o
      activity: true
      title: _(Activity Stream:)

    - id: reports_legend
      title: _(Map Legend:)
      view: LegendView
      icon: info-circle
      items:
        - title: _(Observations)
          image: /static/css/images/markers/marker-observation.png
          url: /filter/observation
        - title: _(Ideas)
          image: /static/css/images/markers/marker-idea.png
          url: /filter/idea
        - title: _(Questions)
          image: /static/css/images/markers/marker-question.png
          url: /filter/question
        - title: _(Complaints)
          image: /static/css/images/markers/marker-complaint.png
          url: /filter/complaint

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: false
  add_button_label: _(Add a report to the map!)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(View All Organizations)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(New post)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)

  location_item_name: location


  #### begin dynamic form config ####
  place_detail:
    - category: network_org
      includeOnForm: true
      name: location_type
      dataset: ymca
      icon_url: /static/css/images/markers/network-marker.png
      value: org
      label: _(Organization)
      fields:
        - name: title
          type: text
          prompt: _(Title of your question:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your question?)"
          display_prompt: _(My question:)
          placeholder: _(Enter question...)

  # define form elements that appear on every form here
  common_form_elements:
    - name: submitter_name
      type: text
      prompt: _(Your name)
      placeholder: _(Name)
      optional: true
    - name: private-submitter_email
      type: text
      prompt: _(Your Email)
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Receive email updates on your report)
        - key: size
          value: 30
    - name: my_image
      type: file
      prompt: _(Image)
      inputfile_label: _(Add an Image)
      optional: true
      attrs:
        - key: accept
          value: image/*
    - type: submit
      label: _(Put it on the map!)

  #### end dynamic form config ####

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Background)
    slug: background
    name: background
    hide_from_top_bar: true

  - title: _(Get involved)
    slug: getinvolved
    name: contribute

